language: node_js

node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "wuhooo" #{GitHub账户名称}
  - git config user.email "gsylzh@163.com" #{Github账户邮箱}
  - git add .
  - git commit -m "Site Update:`TZ=':Asia/Shanghai' date +' %Y-%m-%d %H:%m:%S'`"
  - git push --force --quiet "https://${token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - src #{Hexo源码分支名称}
env:
 global:
   - GH_REF: github.com/wuhooo/wuhooo.github.io.git #{仓库地址}